### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by shinianj** [YH1345246294/DeadMansDraw#2]
我不是来招安的，我只是来说一下，如果想在真寻的插件仓库的readme中让更多人知道，需要在插件仓库的readme中pr仓库地址（官方那边不会去主动收录没pr的插件的，但我看口碑不错所以就来提一下）

**Comment by YH1345246294** [comment]
> 我不是来招安的，我只是来说一下，如果想在真寻的插件仓库的readme中让更多人知道，需要在插件仓库的readme中pr仓库地址（官方那边不会去主动收录没pr的插件的，但我看口碑不错所以就来提一下）

非常感谢，我修改一下readme

**Comment by YH1345246294** [comment]
> 我不是来招安的，我只是来说一下，如果想在真寻的插件仓库的readme中让更多人知道，需要在插件仓库的readme中pr仓库地址（官方那边不会去主动收录没pr的插件的，但我看口碑不错所以就来提一下）

我看到大佬您已经帮我收录了，我不用改了，非常感谢
